import type {
  WidgetType,
  WidgetRegistryEntry,
  WidgetConfig,
  WidgetColSpan,
  WidgetRowSpan,
  WidgetSize,
} from "../types";

// Maps legacy WidgetSize to a column span for backward-compatible hydration
const SIZE_TO_COL: Record<WidgetSize, WidgetColSpan> = {
  sm: 1,
  md: 2,
  lg: 3,
  xl: 4,
};

/**
 * Resolves the effective colSpan and rowSpan for a widget.
 * Uses explicit overrides when present, otherwise falls back to registry defaults,
 * then to legacy `size` mapping. Safe to call with old DB layouts that lack colSpan/rowSpan.
 */
export function resolveWidgetSpan(
  widget: WidgetConfig,
): { col: WidgetColSpan; row: WidgetRowSpan } {
  const registry = WIDGET_REGISTRY[widget.type];
  const col = (widget.colSpan ??
    registry?.defaultColSpan ??
    SIZE_TO_COL[widget.size] ??
    1) as WidgetColSpan;
  const row = (widget.rowSpan ?? registry?.defaultRowSpan ?? 1) as WidgetRowSpan;
  return { col, row };
}

/** Complete registry of all available dashboard widgets */
export const WIDGET_REGISTRY: Record<WidgetType, WidgetRegistryEntry> = {
  total_revenue: {
    type: "total_revenue",
    category: "finance",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "widgets.total_revenue.title",
    descriptionKey: "widgets.total_revenue.description",
    icon: "DollarSign",
    permission: "sales_order.read",
  },
  total_orders: {
    type: "total_orders",
    category: "sales",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "widgets.total_orders.title",
    descriptionKey: "widgets.total_orders.description",
    icon: "ShoppingCart",
    permission: "sales_order.read",
  },
  total_customers: {
    type: "total_customers",
    category: "sales",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "widgets.total_customers.title",
    descriptionKey: "widgets.total_customers.description",
    icon: "Users",
    permission: "customer.read",
  },
  total_products: {
    type: "total_products",
    category: "inventory",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "widgets.total_products.title",
    descriptionKey: "widgets.total_products.description",
    icon: "Package",
    permission: "product.read",
  },
  employee_count: {
    type: "employee_count",
    category: "hr",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "widgets.employee_count.title",
    descriptionKey: "widgets.employee_count.description",
    icon: "UserCheck",
    permission: "employee.read",
  },
  revenue_chart: {
    type: "revenue_chart",
    category: "finance",
    defaultSize: "lg",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.revenue_chart.title",
    descriptionKey: "widgets.revenue_chart.description",
    icon: "TrendingUp",
    permission: "sales_order.read",
  },
  costs_chart: {
    type: "costs_chart",
    category: "finance",
    defaultSize: "lg",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.costs_chart.title",
    descriptionKey: "widgets.costs_chart.description",
    icon: "TrendingDown",
    permission: "journal.read",
  },
  revenue_vs_costs: {
    type: "revenue_vs_costs",
    category: "finance",
    defaultSize: "lg",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.revenue_vs_costs.title",
    descriptionKey: "widgets.revenue_vs_costs.description",
    icon: "BarChart3",
    permission: "journal.read",
  },
  balance_overview: {
    type: "balance_overview",
    category: "finance",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    titleKey: "widgets.balance_overview.title",
    descriptionKey: "widgets.balance_overview.description",
    icon: "Wallet",
    permission: "journal.read",
  },
  costs_by_category: {
    type: "costs_by_category",
    category: "finance",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.costs_by_category.title",
    descriptionKey: "widgets.costs_by_category.description",
    icon: "PieChart",
    permission: "journal.read",
  },
  invoices_summary: {
    type: "invoices_summary",
    category: "finance",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    titleKey: "widgets.invoices_summary.title",
    descriptionKey: "widgets.invoices_summary.description",
    icon: "FileText",
    permission: "customer_invoice.read",
  },
  recent_invoices: {
    type: "recent_invoices",
    category: "finance",
    defaultSize: "lg",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.recent_invoices.title",
    descriptionKey: "widgets.recent_invoices.description",
    icon: "Receipt",
    permission: "customer_invoice.read",
  },
  sales_performance: {
    type: "sales_performance",
    category: "sales",
    defaultSize: "lg",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.sales_performance.title",
    descriptionKey: "widgets.sales_performance.description",
    icon: "Award",
    permission: "sales_order.read",
  },
  delivery_status: {
    type: "delivery_status",
    category: "overview",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    titleKey: "widgets.delivery_status.title",
    descriptionKey: "widgets.delivery_status.description",
    icon: "Truck",
    permission: "delivery_order.read",
  },
  geographic_overview: {
    type: "geographic_overview",
    category: "geographic",
    defaultSize: "xl",
    defaultColSpan: 4,
    defaultRowSpan: 3,
    minColSpan: 3,
    minRowSpan: 2,
    titleKey: "widgets.geographic_overview.title",
    descriptionKey: "widgets.geographic_overview.description",
    icon: "Map",
    permission: "report_geo_performance.read",
  },
  warehouse_overview: {
    type: "warehouse_overview",
    category: "inventory",
    defaultSize: "lg",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.warehouse_overview.title",
    descriptionKey: "widgets.warehouse_overview.description",
    icon: "Warehouse",
    permission: "inventory.read",
  },
  // Composite widgets for the reference Sales Dashboard layout
  revenue_bar_chart: {
    type: "revenue_bar_chart",
    category: "finance",
    defaultSize: "xl",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "revenueChart.title",
    descriptionKey: "revenueChart.subtitle",
    icon: "BarChart3",
    permission: "sales_order.read",
  },
  stat_summary_balance: {
    type: "stat_summary_balance",
    category: "finance",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "stats.totalBalance",
    descriptionKey: "stats.totalBalance",
    icon: "Wallet",
    permission: "journal.read",
  },
  stat_summary_revenue: {
    type: "stat_summary_revenue",
    category: "finance",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "stats.totalRevenue",
    descriptionKey: "stats.totalRevenue",
    icon: "TrendingUp",
    permission: "sales_order.read",
  },
  stat_summary_expense: {
    type: "stat_summary_expense",
    category: "finance",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "stats.totalExpense",
    descriptionKey: "stats.totalExpense",
    icon: "TrendingDown",
    permission: "journal.read",
  },
  stat_summary_orders: {
    type: "stat_summary_orders",
    category: "sales",
    defaultSize: "sm",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    titleKey: "stats.totalOrders",
    descriptionKey: "stats.totalOrders",
    icon: "ShoppingCart",
    permission: "sales_order.read",
  },
  best_selling: {
    type: "best_selling",
    category: "sales",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "bestSelling.title",
    descriptionKey: "bestSelling.subtitle",
    icon: "Star",
    permission: "sales_order.read",
  },
  track_orders: {
    type: "track_orders",
    category: "sales",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "trackOrders.title",
    descriptionKey: "trackOrders.subtitle",
    icon: "Truck",
    permission: "sales_order.read",
  },
  track_purchase_orders: {
    type: "track_purchase_orders",
    category: "purchase",
    defaultSize: "md",
    defaultColSpan: 2,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "trackPurchaseOrders.title",
    descriptionKey: "trackPurchaseOrders.subtitle",
    icon: "PackageCheck",
    permission: "purchase_order.read",
  },
  pending_approvals_sales: {
    type: "pending_approvals_sales",
    category: "sales",
    defaultSize: "xl",
    defaultColSpan: 2,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.pending_approvals_sales.title",
    descriptionKey: "widgets.pending_approvals_sales.description",
    icon: "ClipboardCheck",
  },
  pending_approvals_purchase: {
    type: "pending_approvals_purchase",
    category: "purchase",
    defaultSize: "xl",
    defaultColSpan: 2,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 1,
    titleKey: "widgets.pending_approvals_purchase.title",
    descriptionKey: "widgets.pending_approvals_purchase.description",
    icon: "PackageCheck",
  },
  travel_planner_overview: {
    type: "travel_planner_overview",
    category: "sales",
    defaultSize: "xl",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    minColSpan: 2,
    minRowSpan: 2,
    titleKey: "widgets.travel_planner_overview.title",
    descriptionKey: "widgets.travel_planner_overview.description",
    icon: "Route",
    permission: "travel_planner.read",
  },
};

/** Default layout for new users — mirrors the reference Sales Dashboard design */
export const DEFAULT_WIDGETS: WidgetConfig[] = [
  { id: "w-1", type: "revenue_bar_chart",    title: "", size: "xl", colSpan: 4, rowSpan: 2, order: 0, visible: true },
  { id: "w-2", type: "stat_summary_balance", title: "", size: "sm", colSpan: 1, rowSpan: 1, order: 1, visible: true },
  { id: "w-3", type: "stat_summary_revenue", title: "", size: "sm", colSpan: 1, rowSpan: 1, order: 2, visible: true },
  { id: "w-4", type: "stat_summary_expense", title: "", size: "sm", colSpan: 1, rowSpan: 1, order: 3, visible: true },
  { id: "w-5", type: "stat_summary_orders",  title: "", size: "sm", colSpan: 1, rowSpan: 1, order: 4, visible: true },
  { id: "w-6", type: "best_selling",         title: "", size: "md", colSpan: 2, rowSpan: 2, order: 5, visible: true },
  { id: "w-7", type: "track_orders",         title: "", size: "md", colSpan: 2, rowSpan: 2, order: 6, visible: true },
  { id: "w-8", type: "track_purchase_orders", title: "", size: "md", colSpan: 4, rowSpan: 2, order: 7, visible: true },
];

/** Widget types grouped by category for the picker UI */
export function getWidgetsByCategory() {
  const grouped: Record<string, WidgetRegistryEntry[]> = {};
  for (const entry of Object.values(WIDGET_REGISTRY)) {
    if (!grouped[entry.category]) grouped[entry.category] = [];
    grouped[entry.category].push(entry);
  }
  return grouped;
}
