"use client";

import { Drawer } from "@/components/ui/drawer";
import { useEffect, useRef } from "react";
import { useForm, Controller } from "react-hook-form";
import { useTranslations } from "next-intl";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Field, FieldLabel, FieldError } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { LocationPicker } from "../../../geographic/components/location-picker";

import { useCreateWarehouse, useUpdateWarehouse, useWarehouse } from "../../hooks/use-warehouses";
import type { Warehouse } from "../../types";

// Code is auto-generated by the backend — excluded from the form
const formSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters").max(100),
  description: z.string().max(500).optional(),
  capacity: z.number().min(0).optional().nullable(),
  address: z.string().max(500).optional(),
  province_id: z.string().optional(),
  city_id: z.string().optional(),
  district_id: z.string().optional(),
  village_name: z.string().optional(),
  latitude: z.number().min(-90).max(90).optional().nullable(),
  longitude: z.number().min(-180).max(180).optional().nullable(),
  is_active: z.boolean(),
});

type FormData = z.infer<typeof formSchema>;
type PanelMode = "create" | "edit" | "view";

interface WarehouseSidePanelProps {
  readonly isOpen: boolean;
  readonly onClose: () => void;
  readonly mode: PanelMode;
  readonly warehouse?: Warehouse | null;
  readonly onSuccess?: () => void;
}

export function WarehouseSidePanel({
  isOpen,
  onClose,
  mode,
  warehouse,
  onSuccess,
}: WarehouseSidePanelProps) {
  const t = useTranslations("warehouse");
  const isEditing = mode === "edit";
  const isViewing = mode === "view";
  const createWarehouse = useCreateWarehouse();
  const updateWarehouse = useUpdateWarehouse();

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    control,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      description: "",
      capacity: null,
      address: "",
      province_id: undefined,
      city_id: undefined,
      district_id: undefined,
      village_name: "",
      latitude: -6.2088,
      longitude: 106.8456,
      is_active: true,
    },
  });

  const {
    isLoading: isLoadingDetail,
    refetch: refetchDetail,
  } = useWarehouse(warehouse?.id ?? "", { enabled: false, staleTime: 0 });

  // Stable ref so the setup effect can read the latest warehouse fallback
  // without adding warehouse to its deps (would reset the form on every parent re-render).
  const warehouseRef = useRef(warehouse);
  useEffect(() => {
    warehouseRef.current = warehouse;
  }, [warehouse]);

  useEffect(() => {
    if (!isOpen) return;

    if ((mode === "edit" || mode === "view") && warehouse?.id) {
      void refetchDetail().then((result) => {
        const entity = result.status === "success" && result.data?.data
          ? result.data.data
          : warehouseRef.current;
        if (!entity) return;

        // Resolve geographic IDs — prefer direct FK fields on the entity,
        // fall back to digging through the nested village hierarchy
        const v = entity.village;
        const d = v?.district;
        const c = d?.city;
        const p = c?.province;

        reset({
          name: entity.name,
          description: entity.description ?? "",
          capacity: entity.capacity ?? null,
          address: entity.address ?? "",
          province_id: entity.province_id ?? p?.id ?? undefined,
          city_id: entity.city_id ?? c?.id ?? undefined,
          district_id: entity.district_id ?? d?.id ?? undefined,
          village_name: entity.village_name ?? "",
          latitude: entity.latitude ?? null,
          longitude: entity.longitude ?? null,
          is_active: true,
        });
      });
    } else if (mode === "create") {
      reset({
        name: "",
        description: "",
        capacity: null,
        address: "",
        village_name: "",
        latitude: null,
        longitude: null,
        is_active: true,
      });
    }
  }, [isOpen, mode, warehouse?.id, refetchDetail, reset]);

  const onSubmit = async (data: FormData) => {
    try {
      if (isEditing && warehouse) {
        // Always send all geographic fields so the backend always writes them.
        // `|| null` converts empty/undefined to JSON null → Go nil pointer → DB NULL (clears the column).
        // A truthy UUID string is passed as-is → backend sets the column.
        await updateWarehouse.mutateAsync({
          id: warehouse.id,
          data: {
            name: data.name,
            description: data.description ?? "",
            capacity: data.capacity ?? undefined,
            address: data.address ?? "",
            province_id: data.province_id || null,
            city_id: data.city_id || null,
            district_id: data.district_id || null,
            village_name: data.village_name || undefined,
            latitude: data.latitude,
            longitude: data.longitude,
            is_active: true,
          },
        });
        toast.success(t("warehouse.updateSuccess"));
      } else {
        // For creation, omit empty optional fields entirely.
        await createWarehouse.mutateAsync({
          name: data.name,
          description: data.description || undefined,
          capacity: data.capacity ?? undefined,
          address: data.address || undefined,
          province_id: data.province_id || undefined,
          city_id: data.city_id || undefined,
          district_id: data.district_id || undefined,
          village_name: data.village_name || undefined,
          latitude: data.latitude,
          longitude: data.longitude,
          is_active: true,
        });
        toast.success(t("warehouse.createSuccess"));
      }
      onSuccess?.();
      onClose();
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Failed to save warehouse";
      toast.error(message);
      console.error("Failed to save warehouse:", error);
    }
  };

  const isLoading = createWarehouse.isPending || updateWarehouse.isPending || isLoadingDetail;

  const panelTitle = isViewing
    ? warehouse?.name ?? t("warehouse.title")
    : isEditing
      ? t("warehouse.editTitle")
      : t("warehouse.createTitle");

  return (
    <>
      <Drawer
        open={isOpen}
        onOpenChange={(open) => !open && onClose()}
        title={panelTitle}
        side="right"
        defaultWidth={550}
      >
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6 pb-20 p-4">
          {/* Basic Information Section */}
          <div className="space-y-4">
            <h3 className="text-sm font-medium border-b pb-2">
              {t("warehouse.sections.basicInfo")}
            </h3>
            
            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.name")} *</FieldLabel>
              <Input
                placeholder={t("warehouse.form.namePlaceholder")}
                {...register("name")}
                disabled={isViewing}
              />
              {errors.name && <FieldError>{errors.name.message}</FieldError>}
            </Field>

            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.description")}</FieldLabel>
              <Textarea
                placeholder={t("warehouse.form.descriptionPlaceholder")}
                {...register("description")}
                rows={2}
                disabled={isViewing}
              />
            </Field>

            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.capacity")}</FieldLabel>
              <Controller
                control={control}
                name="capacity"
                render={({ field }) => (
                  <Input
                    type="number"
                    placeholder={t("warehouse.form.capacityPlaceholder")}
                    disabled={isViewing}
                    {...field}
                    value={field.value ?? ""}
                    onChange={(e) => field.onChange(e.target.valueAsNumber || null)}
                  />
                )}
              />
            </Field>


          </div>

          {/* Location Section */}
          <div className="space-y-4 pt-4">
            <h3 className="text-sm font-medium border-b pb-2">
              {t("warehouse.sections.location")}
            </h3>

            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.address")}</FieldLabel>
              <Textarea
                placeholder={t("warehouse.form.addressPlaceholder")}
                {...register("address")}
                rows={2}
                disabled={isViewing}
              />
            </Field>

            <LocationPicker
              control={control}
              setValue={setValue}
              disabled={isViewing}
              enabled={isOpen}
              labels={{
                mapPickerTitle: t("warehouse.mapPicker.title"),
                mapPickerDescription: t("warehouse.mapPicker.description"),
              }}
            />
          </div>

          {/* Actions */}
          {!isViewing && (
            <div className="flex justify-end gap-2 pt-4 border-t sticky bottom-0 bg-background pb-2 z-10">
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                className="cursor-pointer"
              >
                {t("common.cancel")}
              </Button>
              <Button type="submit" disabled={isLoading} className="cursor-pointer">
                {isLoading ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Saving...
                  </>
                ) : isEditing ? (
                  t("common.save")
                ) : (
                  t("common.create")
                )}
              </Button>
            </div>
          )}
        </form>
      </Drawer>
    </>
  );
}
