"use client";

import { Drawer } from "@/components/ui/drawer";
import { useEffect, useState, useRef } from "react";
import { useForm, Controller, useWatch } from "react-hook-form";
import { useTranslations } from "next-intl";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { MapPin, Navigation, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Field, FieldLabel, FieldError } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { MapPickerModal } from "@/components/ui/map/map-picker-modal";

import { useCreateWarehouse, useUpdateWarehouse, useWarehouse } from "../../hooks/use-warehouses";
import { useProvinces } from "../../../geographic/hooks/use-provinces";
import { useCities } from "../../../geographic/hooks/use-cities";
import { useDistricts } from "../../../geographic/hooks/use-districts";
import { useVillages } from "../../../geographic/hooks/use-villages";
import type { Warehouse } from "../../types";

// Code is auto-generated by the backend — excluded from the form
const formSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters").max(100),
  description: z.string().max(500).optional(),
  capacity: z.number().min(0).optional().nullable(),
  address: z.string().max(500).optional(),
  province_id: z.string().optional(),
  city_id: z.string().optional(),
  district_id: z.string().optional(),
  village_id: z.string().optional(),
  latitude: z.number().min(-90).max(90).optional().nullable(),
  longitude: z.number().min(-180).max(180).optional().nullable(),
  is_active: z.boolean(),
});

type FormData = z.infer<typeof formSchema>;
type PanelMode = "create" | "edit" | "view";

interface WarehouseSidePanelProps {
  readonly isOpen: boolean;
  readonly onClose: () => void;
  readonly mode: PanelMode;
  readonly warehouse?: Warehouse | null;
  readonly onSuccess?: () => void;
}

export function WarehouseSidePanel({
  isOpen,
  onClose,
  mode,
  warehouse,
  onSuccess,
}: WarehouseSidePanelProps) {
  const t = useTranslations("warehouse");
  const isEditing = mode === "edit";
  const isViewing = mode === "view";
  const createWarehouse = useCreateWarehouse();
  const updateWarehouse = useUpdateWarehouse();
  const [isMapPickerOpen, setIsMapPickerOpen] = useState(false);

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    control,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      description: "",
      capacity: null,
      address: "",
      province_id: undefined,
      city_id: undefined,
      district_id: undefined,
      village_id: "",
      latitude: -6.2088,
      longitude: 106.8456,
      is_active: true,
    },
  });

  // React Compiler-compatible reactive watches
  const provinceId = useWatch({ control, name: "province_id" });
  const cityId = useWatch({ control, name: "city_id" });
  const districtId = useWatch({ control, name: "district_id" });
  const latitude = useWatch({ control, name: "latitude" });
  const longitude = useWatch({ control, name: "longitude" });

  const {
    isLoading: isLoadingDetail,
    refetch: refetchDetail,
  } = useWarehouse(warehouse?.id ?? "", { enabled: false, staleTime: 0 });

  // Stable ref so the setup effect can read the latest warehouse fallback
  // without adding warehouse to its deps (would reset the form on every parent re-render).
  const warehouseRef = useRef(warehouse);
  useEffect(() => {
    warehouseRef.current = warehouse;
  }, [warehouse]);

  const { data: provincesData } = useProvinces({ per_page: 100 }, { enabled: isOpen });
  const { data: citiesData } = useCities(
    provinceId ? { province_id: String(provinceId), per_page: 100 } : undefined,
    { enabled: isOpen && !!provinceId }
  );
  const { data: districtsData } = useDistricts(
    cityId ? { city_id: String(cityId), per_page: 100 } : undefined,
    { enabled: isOpen && !!cityId }
  );
  const { data: villagesData } = useVillages(
    districtId ? { district_id: String(districtId), per_page: 100 } : undefined,
    { enabled: isOpen && !!districtId }
  );

  const provinces = provincesData?.data ?? [];
  const cities = citiesData?.data ?? [];
  const districts = districtsData?.data ?? [];
  const villages = villagesData?.data ?? [];

  useEffect(() => {
    if (!isOpen) return;

    if ((mode === "edit" || mode === "view") && warehouse?.id) {
      void refetchDetail().then((result) => {
        const entity = result.status === "success" && result.data?.data
          ? result.data.data
          : warehouseRef.current;
        if (!entity) return;

        // Resolve geographic IDs — prefer direct FK fields on the entity,
        // fall back to digging through the nested village hierarchy
        const v = entity.village;
        const d = v?.district;
        const c = d?.city;
        const p = c?.province;

        reset({
          name: entity.name,
          description: entity.description ?? "",
          capacity: entity.capacity ?? null,
          address: entity.address ?? "",
          province_id: entity.province_id ?? p?.id ?? undefined,
          city_id: entity.city_id ?? c?.id ?? undefined,
          district_id: entity.district_id ?? d?.id ?? undefined,
          village_id: entity.village_id ?? "",
          latitude: entity.latitude ?? null,
          longitude: entity.longitude ?? null,
          is_active: entity.is_active,
        });
      });
    } else if (mode === "create") {
      reset({
        name: "",
        description: "",
        capacity: null,
        address: "",
        village_id: "",
        latitude: null,
        longitude: null,
        is_active: true,
      });
    }
  }, [isOpen, mode, warehouse?.id, refetchDetail, reset]);

  const onSubmit = async (data: FormData) => {
    try {
      if (isEditing && warehouse) {
        // Always send all geographic fields so the backend always writes them.
        // `|| null` converts empty/undefined to JSON null → Go nil pointer → DB NULL (clears the column).
        // A truthy UUID string is passed as-is → backend sets the column.
        await updateWarehouse.mutateAsync({
          id: warehouse.id,
          data: {
            name: data.name,
            description: data.description ?? "",
            capacity: data.capacity ?? undefined,
            address: data.address ?? "",
            province_id: data.province_id || null,
            city_id: data.city_id || null,
            district_id: data.district_id || null,
            village_id: data.village_id || null,
            latitude: data.latitude,
            longitude: data.longitude,
            is_active: data.is_active,
          },
        });
        toast.success(t("warehouse.updateSuccess"));
      } else {
        // For creation, omit empty optional fields entirely.
        await createWarehouse.mutateAsync({
          name: data.name,
          description: data.description || undefined,
          capacity: data.capacity ?? undefined,
          address: data.address || undefined,
          province_id: data.province_id || undefined,
          city_id: data.city_id || undefined,
          district_id: data.district_id || undefined,
          village_id: data.village_id || undefined,
          latitude: data.latitude,
          longitude: data.longitude,
          is_active: data.is_active,
        });
        toast.success(t("warehouse.createSuccess"));
      }
      onSuccess?.();
      onClose();
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Failed to save warehouse";
      toast.error(message);
      console.error("Failed to save warehouse:", error);
    }
  };

  const handleCoordinateSelect = (lat: number, lng: number) => {
    setValue("latitude", lat, { shouldValidate: true, shouldDirty: true });
    setValue("longitude", lng, { shouldValidate: true, shouldDirty: true });
  };

  const isLoading = createWarehouse.isPending || updateWarehouse.isPending || isLoadingDetail;

  const panelTitle = isViewing
    ? warehouse?.name ?? t("warehouse.title")
    : isEditing
      ? t("warehouse.editTitle")
      : t("warehouse.createTitle");

  return (
    <>
      <Drawer
        open={isOpen}
        onOpenChange={(open) => !open && onClose()}
        title={panelTitle}
        side="right"
        defaultWidth={550}
      >
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6 pb-20 p-4">
          {/* Basic Information Section */}
          <div className="space-y-4">
            <h3 className="text-sm font-medium border-b pb-2">
              {t("warehouse.sections.basicInfo")}
            </h3>
            
            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.name")} *</FieldLabel>
              <Input
                placeholder={t("warehouse.form.namePlaceholder")}
                {...register("name")}
                disabled={isViewing}
              />
              {errors.name && <FieldError>{errors.name.message}</FieldError>}
            </Field>

            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.description")}</FieldLabel>
              <Textarea
                placeholder={t("warehouse.form.descriptionPlaceholder")}
                {...register("description")}
                rows={2}
                disabled={isViewing}
              />
            </Field>

            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.capacity")}</FieldLabel>
              <Controller
                control={control}
                name="capacity"
                render={({ field }) => (
                  <Input
                    type="number"
                    placeholder={t("warehouse.form.capacityPlaceholder")}
                    disabled={isViewing}
                    {...field}
                    value={field.value ?? ""}
                    onChange={(e) => field.onChange(e.target.valueAsNumber || null)}
                  />
                )}
              />
            </Field>

            {!isViewing && (
              <Controller
                control={control}
                name="is_active"
                render={({ field }) => (
                  <Field
                    orientation="horizontal"
                    className="flex items-center justify-between rounded-lg border p-3"
                  >
                    <FieldLabel>{t("warehouse.form.isActive")}</FieldLabel>
                    <Switch
                      checked={field.value}
                      onCheckedChange={field.onChange}
                    />
                  </Field>
                )}
              />
            )}
          </div>

          {/* Location Section */}
          <div className="space-y-4 pt-4">
            <h3 className="text-sm font-medium border-b pb-2">
              {t("warehouse.sections.location")}
            </h3>

            <Field orientation="vertical">
              <FieldLabel>{t("warehouse.form.address")}</FieldLabel>
              <Textarea
                placeholder={t("warehouse.form.addressPlaceholder")}
                {...register("address")}
                rows={2}
                disabled={isViewing}
              />
            </Field>

            <div className="grid grid-cols-2 gap-4">
              <Field orientation="vertical">
                <FieldLabel>{t("warehouse.form.province")}</FieldLabel>
                <Controller
                  control={control}
                  name="province_id"
                  render={({ field }) => (
                    <Select
                      value={field.value ?? ""}
                      onValueChange={(val) => {
                        field.onChange(val);
                        setValue("city_id", undefined, { shouldDirty: true });
                        setValue("district_id", undefined, { shouldDirty: true });
                        setValue("village_id", undefined, { shouldDirty: true });
                      }}
                      disabled={isViewing}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select Province" />
                      </SelectTrigger>
                      <SelectContent>
                        {provinces.map((p) => (
                          <SelectItem key={p.id} value={p.id}>
                            {p.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                />
              </Field>

              <Field orientation="vertical">
                <FieldLabel>{t("warehouse.form.city")}</FieldLabel>
                <Controller
                  control={control}
                  name="city_id"
                  render={({ field }) => (
                    <Select
                      key={`city-${provinceId ?? ""}`}
                      value={field.value ?? ""}
                      onValueChange={(val) => {
                        field.onChange(val);
                        setValue("district_id", undefined, { shouldDirty: true });
                        setValue("village_id", undefined, { shouldDirty: true });
                      }}
                      disabled={isViewing}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select City" />
                      </SelectTrigger>
                      <SelectContent>
                        {provinceId ? cities.map((c) => (
                          <SelectItem key={c.id} value={c.id}>
                            {c.name}
                          </SelectItem>
                        )) : (
                          <SelectItem value="_" disabled>
                            Select province first
                          </SelectItem>
                        )}
                      </SelectContent>
                    </Select>
                  )}
                />
              </Field>

              <Field orientation="vertical">
                <FieldLabel>{t("warehouse.form.district")}</FieldLabel>
                <Controller
                  control={control}
                  name="district_id"
                  render={({ field }) => (
                    <Select
                      key={`district-${cityId ?? ""}`}
                      value={field.value ?? ""}
                      onValueChange={(val) => {
                        field.onChange(val);
                        setValue("village_id", undefined, { shouldDirty: true });
                      }}
                      disabled={isViewing}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select District" />
                      </SelectTrigger>
                      <SelectContent>
                        {cityId ? districts.map((d) => (
                          <SelectItem key={d.id} value={d.id}>
                            {d.name}
                          </SelectItem>
                        )) : (
                          <SelectItem value="_" disabled>
                            Select city first
                          </SelectItem>
                        )}
                      </SelectContent>
                    </Select>
                  )}
                />
              </Field>

              <Field orientation="vertical">
                <FieldLabel>{t("warehouse.form.village")}</FieldLabel>
                <Controller
                  control={control}
                  name="village_id"
                  render={({ field }) => (
                    <Select
                      key={`village-${districtId ?? ""}`}
                      value={field.value ?? ""}
                      onValueChange={field.onChange}
                      disabled={isViewing}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select Village" />
                      </SelectTrigger>
                      <SelectContent>
                        {districtId ? villages.map((v) => (
                          <SelectItem key={v.id} value={v.id}>
                            {v.name}
                          </SelectItem>
                        )) : (
                          <SelectItem value="_" disabled>
                            Select district first
                          </SelectItem>
                        )}
                      </SelectContent>
                    </Select>
                  )}
                />
              </Field>
            </div>

            {/* Coordinates */}
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b pb-2">
                <div className="flex items-center gap-2">
                  <Navigation className="h-4 w-4" />
                  <h3 className="text-sm font-medium">{t("warehouse.sections.coordinates")}</h3>
                </div>
                {!isViewing && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => setIsMapPickerOpen(true)}
                    className="cursor-pointer"
                  >
                    <MapPin className="h-3 w-3 mr-1" />
                    {t("warehouse.pickFromMap")}
                  </Button>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <Field orientation="vertical">
                  <FieldLabel>{t("warehouse.form.latitude")}</FieldLabel>
                  <Controller
                    control={control}
                    name="latitude"
                    render={({ field }) => (
                      <Input
                        type="number"
                        step="any"
                        placeholder="-6.2088"
                        disabled={isViewing}
                        {...field}
                        value={field.value ?? ""}
                        onChange={(e) => field.onChange(e.target.valueAsNumber)}
                      />
                    )}
                  />
                </Field>
                <Field orientation="vertical">
                  <FieldLabel>{t("warehouse.form.longitude")}</FieldLabel>
                  <Controller
                    control={control}
                    name="longitude"
                    render={({ field }) => (
                      <Input
                        type="number"
                        step="any"
                        placeholder="106.8456"
                        disabled={isViewing}
                        {...field}
                        value={field.value ?? ""}
                        onChange={(e) => field.onChange(e.target.valueAsNumber)}
                      />
                    )}
                  />
                </Field>
              </div>
            </div>
          </div>

          {/* Actions */}
          {!isViewing && (
            <div className="flex justify-end gap-2 pt-4 border-t sticky bottom-0 bg-background pb-2 z-10">
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                className="cursor-pointer"
              >
                {t("common.cancel")}
              </Button>
              <Button type="submit" disabled={isLoading} className="cursor-pointer">
                {isLoading ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Saving...
                  </>
                ) : isEditing ? (
                  t("common.save")
                ) : (
                  t("common.create")
                )}
              </Button>
            </div>
          )}
        </form>
      </Drawer>

      <MapPickerModal
        open={isMapPickerOpen}
        onOpenChange={setIsMapPickerOpen}
        latitude={latitude ?? -6.2088}
        longitude={longitude ?? 106.8456}
        onCoordinateSelect={handleCoordinateSelect}
        title={t("warehouse.mapPicker.title")}
        description={t("warehouse.mapPicker.description")}
      />
    </>
  );
}
