import {
  LayoutDashboard,
  Users,
  UserCircle,
  Calendar,
  FileText,
  Pill,
  Package,
  ShoppingCart,
  Receipt,
  Database,
  BarChart3,
  Activity,
  Stethoscope,
  ClipboardList,
  Warehouse,
  Truck,
  FolderTree,
  MapPin,
  Building2,
  Ruler,
  Store,
  Grid,
  Briefcase,
  Heart,
  TrendingUp,
  Contact,
  Bot,
  Sparkles,
  Handshake,
  DollarSign,
  Settings,
  Shield,
  Menu,
  Tag,
  Layers,
  CreditCard,
  Clock,
  Package2,
  Box,
  Map,
  UserCheck,
  Home,
  PieChart,
  Globe,
  UserPlus,
  Calculator,
  Funnel,
  File,
  FileMinus,
  Target,
  BarChart2,
  Book,
  BookOpen,
  ShieldCheck,
  Edit3,
  List,
  ArrowRightLeft,
  TrendingDown,
  ShoppingBag,
  Star,
} from "lucide-react";

const iconMap: Record<string, React.ReactNode> = {
  // Dashboard icons
  dashboard: <LayoutDashboard className="h-4 w-4" />,
  "layout-dashboard": <LayoutDashboard className="h-4 w-4" />,

  // Data Master icons
  database: <Database className="h-4 w-4" />,
  building: <Building2 className="h-4 w-4" />,
  "building-2": <Building2 className="h-4 w-4" />,
  grid: <Grid className="h-4 w-4" />,
  briefcase: <Briefcase className="h-4 w-4" />,
  user: <UserCircle className="h-4 w-4" />,
  users: <Users className="h-4 w-4" />,
  heart: <Heart className="h-4 w-4" />,
  handshake: <Handshake className="h-4 w-4" />,
  "dollar-sign": <DollarSign className="h-4 w-4" />,
  dollarsign: <DollarSign className="h-4 w-4" />,
  settings: <Settings className="h-4 w-4" />,
  shield: <Shield className="h-4 w-4" />,
  menu: <Menu className="h-4 w-4" />,
  tag: <Tag className="h-4 w-4" />,
  layers: <Layers className="h-4 w-4" />,
  "credit-card": <CreditCard className="h-4 w-4" />,
  creditcard: <CreditCard className="h-4 w-4" />,
  clock: <Clock className="h-4 w-4" />,
  "package-2": <Package2 className="h-4 w-4" />,
  package2: <Package2 className="h-4 w-4" />,
  box: <Box className="h-4 w-4" />,
  map: <Map className="h-4 w-4" />,
  "user-check": <UserCheck className="h-4 w-4" />,
  usercheck: <UserCheck className="h-4 w-4" />,
  home: <Home className="h-4 w-4" />,
  "pie-chart": <PieChart className="h-4 w-4" />,
  piechart: <PieChart className="h-4 w-4" />,
  globe: <Globe className="h-4 w-4" />,
  "user-plus": <UserPlus className="h-4 w-4" />,
  userplus: <UserPlus className="h-4 w-4" />,
  calculator: <Calculator className="h-4 w-4" />,
  funnel: <Funnel className="h-4 w-4" />,
  file: <File className="h-4 w-4" />,
  "file-minus": <FileMinus className="h-4 w-4" />,
  fileminus: <FileMinus className="h-4 w-4" />,
  target: <Target className="h-4 w-4" />,
  "bar-chart-2": <BarChart2 className="h-4 w-4" />,
  barchart2: <BarChart2 className="h-4 w-4" />,
  book: <Book className="h-4 w-4" />,
  "book-open": <BookOpen className="h-4 w-4" />,
  bookopen: <BookOpen className="h-4 w-4" />,
  "shield-check": <ShieldCheck className="h-4 w-4" />,
  shieldcheck: <ShieldCheck className="h-4 w-4" />,
  "edit-3": <Edit3 className="h-4 w-4" />,
  edit3: <Edit3 className="h-4 w-4" />,
  list: <List className="h-4 w-4" />,
  "arrow-right-left": <ArrowRightLeft className="h-4 w-4" />,
  arrowrightleft: <ArrowRightLeft className="h-4 w-4" />,
  "trending-down": <TrendingDown className="h-4 w-4" />,
  trendingdown: <TrendingDown className="h-4 w-4" />,
  "shopping-bag": <ShoppingBag className="h-4 w-4" />,
  shoppingbag: <ShoppingBag className="h-4 w-4" />,
  star: <Star className="h-4 w-4" />,

  // Sales icons
  "trending-up": <TrendingUp className="h-4 w-4" />,
  trendingup: <TrendingUp className="h-4 w-4" />,
  contact: <Contact className="h-4 w-4" />,

  // Other icons
  calendar: <Calendar className="h-4 w-4" />,
  filetext: <FileText className="h-4 w-4" />,
  "file-text": <FileText className="h-4 w-4" />,
  pill: <Pill className="h-4 w-4" />,
  package: <Package className="h-4 w-4" />,
  shoppingcart: <ShoppingCart className="h-4 w-4" />,
  "shopping-cart": <ShoppingCart className="h-4 w-4" />,
  receipt: <Receipt className="h-4 w-4" />,
  barchart3: <BarChart3 className="h-4 w-4" />,
  "bar-chart-3": <BarChart3 className="h-4 w-4" />,
  activity: <Activity className="h-4 w-4" />,
  stethoscope: <Stethoscope className="h-4 w-4" />,
  clipboardlist: <ClipboardList className="h-4 w-4" />,
  warehouse: <Warehouse className="h-4 w-4" />,
  truck: <Truck className="h-4 w-4" />,
  foldertree: <FolderTree className="h-4 w-4" />,
  mappin: <MapPin className="h-4 w-4" />,
  ruler: <Ruler className="h-4 w-4" />,
  store: <Store className="h-4 w-4" />,
  "map-pin": <MapPin className="h-4 w-4" />,
  "clipboard-list": <ClipboardList className="h-4 w-4" />,
  bot: <Bot className="h-4 w-4" />,
  sparkles: <Sparkles className="h-4 w-4" />,
  "ai-chatbot": <Bot className="h-4 w-4" />,
  "ai-settings": <Sparkles className="h-4 w-4" />,
};

export function getMenuIcon(iconName: string): React.ReactNode {
  return iconMap[iconName.toLowerCase()] || <Database className="h-4 w-4" />;
}
