export interface NavItem {
  id?: string;
  name: string;
  i18nKey?: string;
  icon: string; // string key for lib/menu-icons.tsx
  url: string;
  permission?: string;
  children?: NavItem[];
}

export const navigationConfig: NavItem[] = [
  {
    name: "Dashboard",
    i18nKey: "dashboard",
    icon: "layout-dashboard",
    url: "/dashboard",
    permission: "dashboard.view",
  },
  // CRM before Sales (lead -> opportunity -> order flow)
  {
    name: "CRM",
    i18nKey: "crm",
    icon: "handshake",
    url: "/crm",
    children: [
      {
        name: "Leads",
        i18nKey: "leads",
        url: "/crm/leads",
        icon: "users",
        permission: "crm_lead.read",
      },
      {
        name: "Pipeline",
        i18nKey: "pipeline",
        url: "/crm/pipeline",
        icon: "kanban",
        permission: "crm_deal.read",
      },
      {
        name: "Tasks",
        i18nKey: "tasks",
        url: "/crm/tasks",
        icon: "check-square",
        permission: "crm_task.read",
      },
      {
        name: "Visit Reports",
        i18nKey: "visitReports",
        url: "/crm/visits",
        icon: "map-pin",
        permission: "crm_visit.read",
      },
      {
        name: "Area Mapping",
        i18nKey: "areaMapping",
        url: "/crm/area-mapping",
        icon: "map",
        permission: "crm_area_mapping.read",
      },
      {
        name: "Sales Target",
        i18nKey: "salesTarget",
        url: "/crm/targets",
        icon: "check-square",
        permission: "sales_target.read",
      },
      {
        name: "CRM Settings",
        i18nKey: "crmSettings",
        url: "/crm/settings",
        icon: "settings",
        children: [
          {
            name: "Pipeline Stages",
            i18nKey: "pipelineStages",
            url: "/crm/settings/pipeline-stages",
            icon: "layers",
            permission: "crm_pipeline_stage.read",
          },
          {
            name: "Lead Sources",
            i18nKey: "leadSources",
            url: "/crm/settings/lead-sources",
            icon: "funnel",
            permission: "crm_lead_source.read",
          },
          {
            name: "Lead Statuses",
            i18nKey: "leadStatuses",
            url: "/crm/settings/lead-statuses",
            icon: "tag",
            permission: "crm_lead_status.read",
          },
          {
            name: "Contact Roles",
            i18nKey: "contactRoles",
            url: "/crm/settings/contact-roles",
            icon: "user-cog",
            permission: "crm_contact_role.read",
          },
          {
            name: "Activity Types",
            i18nKey: "activityTypes",
            url: "/crm/settings/activity-types",
            icon: "zap",
            permission: "crm_activity_type.read",
          },
        ],
      },
    ],
  },
  {
    name: "Travel Planner",
    i18nKey: "travelPlanner",
    icon: "route",
    url: "/travel/travel-planner",
    permission: "travel_planner.read",
    children: [
      {
        name: "Planner Workspace",
        i18nKey: "plannerWorkspace",
        url: "/travel/travel-planner",
        icon: "map",
        permission: "travel_planner.read",
      },
      {
        name: "Visit Planner",
        i18nKey: "visitPlanner",
        url: "/travel/visit-planner",
        icon: "map-pin",
        permission: "travel.visit.read",
      },
    ],
  },
  {
    name: "Sales",
    i18nKey: "sales",
    icon: "shopping-cart",
    url: "/sales",
    children: [
      {
        name: "Quotations",
        i18nKey: "quotations",
        url: "/sales/quotations",
        icon: "file-text",
        permission: "sales_quotation.read",
      },
      {
        name: "Sales Orders",
        i18nKey: "salesOrders",
        url: "/sales/orders",
        icon: "shopping-cart",
        permission: "sales_order.read",
      },
      {
        name: "Delivery Orders",
        i18nKey: "deliveryOrders",
        url: "/sales/delivery-orders",
        icon: "truck",
        permission: "delivery_order.read",
      },
      {
        name: "Customer Invoices",
        i18nKey: "customerInvoices",
        url: "/sales/invoices",
        icon: "receipt",
        permission: "customer_invoice.read",
      },
      {
        name: "Customer Invoices DP",
        i18nKey: "customerInvoicesDP",
        url: "/sales/customer-invoice-down-payments",
        icon: "banknote",
        permission: "customer_invoice_dp.read",
      },
      {
        name: "Returns",
        i18nKey: "returns",
        url: "/sales/returns",
        icon: "rotate-ccw",
        permission: "sales_return.read",
      },
      {
        name: "Payments",
        i18nKey: "payments",
        url: "/sales/payments",
        icon: "credit-card",
        permission: "sales_payment.read",
      },
      {
        name: "Receivables Recap",
        i18nKey: "receivablesRecap",
        url: "/sales/receivables-recap",
        icon: "bar-chart-3",
        permission: "sales_payment.read",
      },
    ],
  },
  {
    name: "Purchase",
    i18nKey: "purchase",
    icon: "truck",
    url: "/purchase",
    children: [
      {
        name: "Requisitions",
        i18nKey: "requisitions",
        url: "/purchase/purchase-requisitions",
        icon: "clipboard-list",
        permission: "purchase_requisition.read",
      },
      {
        name: "Purchase Orders",
        i18nKey: "purchaseOrders",
        url: "/purchase/purchase-orders",
        icon: "shopping-cart",
        permission: "purchase_order.read",
      },
      {
        name: "Goods Receipt",
        i18nKey: "goodsReceipt",
        url: "/purchase/goods-receipt",
        icon: "package",
        permission: "goods_receipt.read",
      },
      {
        name: "Supplier Invoices",
        i18nKey: "supplierInvoices",
        url: "/purchase/supplier-invoices",
        icon: "receipt",
        permission: "supplier_invoice.read",
      },
      {
        name: "Supplier Invoices DP",
        i18nKey: "supplierInvoicesDP",
        url: "/purchase/supplier-invoice-down-payments",
        icon: "banknote",
        permission: "supplier_invoice_dp.read",
      },
      {
        name: "Returns",
        i18nKey: "returns",
        url: "/purchase/returns",
        icon: "rotate-ccw",
        permission: "purchase_return.read",
      },
      {
        name: "Payments",
        i18nKey: "payments",
        url: "/purchase/payments",
        icon: "credit-card",
        permission: "purchase_payment.read",
      },
      {
        name: "Payable Recap",
        i18nKey: "payableRecap",
        url: "/purchase/payable-recap",
        icon: "bar-chart-3",
        permission: "purchase_payment.read",
      },
    ],
  },
  {
    name: "Stock",
    i18nKey: "stock",
    icon: "warehouse",
    url: "/stock",
    children: [
      {
        name: "Inventory",
        i18nKey: "inventory",
        url: "/stock/inventory",
        icon: "box",
        permission: "inventory.read",
      },
      {
        name: "Stock Movement",
        i18nKey: "stockMovement",
        url: "/stock/movements",
        icon: "arrow-right-left",
        permission: "stock_movement.read",
      },
      {
        name: "Stock Opname",
        i18nKey: "stockOpname",
        url: "/stock/opname",
        icon: "clipboard-list",
        permission: "stock_opname.read",
      },
    ],
  },
  {
    name: "Finance",
    i18nKey: "finance",
    icon: "credit-card",
    url: "/finance",
    children: [
      {
        name: "Accounting",
        i18nKey: "accounting",
        url: "",
        icon: "book-open",
        children: [
          {
            name: "Chart of Accounts",
            i18nKey: "chartOfAccounts",
            url: "/finance/accounting/coa",
            icon: "book-open",
            permission: "coa.read",
          },
          {
            name: "Journal",
            i18nKey: "journal",
            url: "",
            icon: "book-open",
            children: [
              {
                name: "Journal Entries",
                i18nKey: "journalEntries",
                url: "/finance/accounting/journal-entries",
                icon: "file-text",
                permission: "journal.read",
              },
              {
                name: "Sales Journal",
                i18nKey: "salesJournal",
                url: "/finance/ar/customer-invoices",
                icon: "receipt",
                permission: "sales_journal.read",
              },
              {
                name: "Purchase Journal",
                i18nKey: "purchaseJournal",
                url: "/finance/accounting/journal-entries/purchase",
                icon: "shopping-cart",
                permission: "purchase_journal.read",
              },
              {
                name: "Adjustment Journal",
                i18nKey: "adjustmentJournal",
                url: "/finance/accounting/journal-entries/adjustment",
                icon: "edit-3",
                permission: "adjustment_journal.read",
              },
            ],
          },
          {
            name: "Financial Closing",
            i18nKey: "financialClosing",
            url: "/finance/accounting/closing",
            icon: "shield-check",
            permission: "financial_closing.read",
          },
        ],
      },
      {
        name: "Accounts Receivable (AR)",
        i18nKey: "accountsReceivable",
        url: "",
        icon: "receipt",
        children: [
          {
            name: "Customer Invoices",
            i18nKey: "customerInvoices",
            url: "/finance/ar/customer-invoices",
            icon: "receipt",
            permission: "sales_journal.read",
          },
          {
            name: "Customer Payments",
            i18nKey: "payments",
            url: "/finance/ar/customer-payments",
            icon: "credit-card",
            permission: "payment.read",
          },
          {
            name: "Credit Notes",
            i18nKey: "returns",
            url: "/finance/ar/credit-notes",
            icon: "rotate-ccw",
            permission: "sales_return.read",
          },
          {
            name: "AR Aging Reports",
            i18nKey: "agingReports",
            url: "/finance/ar/aging-reports",
            icon: "clock",
            permission: "aging_report.read",
          },
        ],
      },
      {
        name: "Accounts Payable (AP)",
        i18nKey: "accountsPayable",
        url: "",
        icon: "receipt",
        children: [
          {
            name: "Supplier Invoices",
            i18nKey: "supplierInvoices",
            url: "/finance/ap/supplier-invoices",
            icon: "receipt",
            permission: "supplier_invoice.read",
          },
          {
            name: "Supplier Payments",
            i18nKey: "payments",
            url: "/finance/ap/supplier-payments",
            icon: "credit-card",
            permission: "payment.read",
          },
          {
            name: "Debit Notes",
            i18nKey: "returns",
            url: "/finance/ap/debit-notes",
            icon: "rotate-ccw",
            permission: "purchase_return.read",
          },
          {
            name: "Non-Trade Payables",
            i18nKey: "nonTradePayables",
            url: "/finance/ap/non-trade-payables",
            icon: "file-text",
            permission: "non_trade_payable.read",
          },
          {
            name: "AP Aging Reports",
            i18nKey: "agingReports",
            url: "/finance/ap/aging-reports",
            icon: "clock",
            permission: "aging_report.read",
          },
        ],
      },
      {
        name: "Cash & Bank",
        i18nKey: "cashBank",
        url: "",
        icon: "landmark",
        children: [
          {
            name: "Bank Accounts",
            i18nKey: "bankAccounts",
            url: "/finance/cash-bank/bank-accounts",
            icon: "landmark",
            permission: "bank_account.read",
          },
          {
            name: "Cash & Bank Journal",
            i18nKey: "cashBankJournal",
            url: "/finance/cash-bank/journals",
            icon: "book-open",
            permission: "cash_bank_journal.read",
          },
          {
            name: "Bank Transfers",
            i18nKey: "bankTransfers",
            url: "/finance/cash-bank/transfers",
            icon: "arrow-right-left",
            permission: "cash_bank_journal.read",
          },
          {
            name: "Bank Reconciliation",
            i18nKey: "bankReconciliation",
            url: "/finance/cash-bank/reconciliation",
            icon: "scale",
            permission: "cash_bank_journal.read",
          },
        ],
      },
      {
        name: "Fixed Assets",
        i18nKey: "fixedAssets",
        url: "",
        icon: "building-2",
        children: [
          {
            name: "Asset Register",
            i18nKey: "assets",
            url: "/finance/fixed-assets/assets",
            icon: "building-2",
            permission: "asset.read",
          },
          {
            name: "Asset Categories",
            i18nKey: "assetCategories",
            url: "/finance/fixed-assets/categories",
            icon: "folder-tree",
            permission: "asset_category.read",
          },
          {
            name: "Asset Locations",
            i18nKey: "assetLocations",
            url: "/finance/fixed-assets/locations",
            icon: "map-pin",
            permission: "asset_location.read",
          },
          {
            name: "Depreciation Schedule",
            i18nKey: "depreciationSchedule",
            url: "/finance/fixed-assets/depreciation-schedule",
            icon: "calendar-clock",
            permission: "asset.depreciate",
          },
          {
            name: "Asset Disposal",
            i18nKey: "assetDisposal",
            url: "/finance/fixed-assets/disposal",
            icon: "hammer",
            permission: "asset_disposal.read",
          },
          {
            name: "Asset Revaluation",
            i18nKey: "assetRevaluation",
            url: "/finance/fixed-assets/revaluation",
            icon: "scale",
            permission: "asset.read",
          },
        ],
      },
      {
        name: "Financial Reports",
        i18nKey: "financialReports",
        url: "",
        icon: "bar-chart-3",
        children: [
          {
            name: "General Ledger",
            i18nKey: "generalLedger",
            url: "/finance/reports/general-ledger",
            icon: "book-open",
            permission: "general_ledger_report.read",
          },
          {
            name: "Trial Balance",
            i18nKey: "trialBalance",
            url: "/finance/reports/trial-balance",
            icon: "scale",
            permission: "trial_balance_report.read",
          },
          {
            name: "Balance Sheet",
            i18nKey: "balanceSheet",
            url: "/finance/reports/balance-sheet",
            icon: "scale",
            permission: "balance_sheet_report.read",
          },
          {
            name: "Profit & Loss",
            i18nKey: "profitLoss",
            url: "/finance/reports/profit-loss",
            icon: "trending-up",
            permission: "profit_loss_report.read",
          },
          {
            name: "Cash Flow Statement",
            i18nKey: "cashFlowStatement",
            url: "/finance/reports/cash-flow-statement",
            icon: "bar-chart-2",
            permission: "cash_flow_statement.read",
          },
        ],
      },
      {
        name: "Finance Settings",
        i18nKey: "financeSettings",
        url: "",
        icon: "settings",
        children: [
          {
            name: "Accounting Mapping",
            i18nKey: "accountingMapping",
            url: "/finance/settings/accounting-mapping",
            icon: "file-text",
            permission: "account_mappings.read",
          },
          {
            name: "Fiscal Years",
            i18nKey: "fiscalYears",
            url: "/finance/settings/fiscal-years",
            icon: "calendar-range",
            permission: "finance_settings.read",
          },
          {
            name: "Tax Configuration",
            i18nKey: "taxConfig",
            url: "/finance/settings/tax-config",
            icon: "receipt",
            permission: "tax_invoice.read",
          },
          {
            name: "Payment Terms",
            i18nKey: "paymentTerms",
            url: "/finance/settings/payment-terms",
            icon: "clock",
            permission: "payment_term.read",
          },
          {
            name: "Currency",
            i18nKey: "currencies",
            url: "/finance/settings/currency",
            icon: "coins",
            permission: "currency.read",
          },
        ],
      },
    ],
  },
  {
    name: "HRD",
    i18nKey: "hrd",
    icon: "users",
    url: "/hrd",
    children: [
      {
        name: "Attendance",
        i18nKey: "attendance",
        url: "/hrd/attendance",
        icon: "clock",
        permission: "attendance.read",
      },
      {
        name: "Leave Requests",
        i18nKey: "leaveRequests",
        url: "/hrd/leave-requests",
        icon: "calendar",
        permission: "leave_request.read",
      },
      {
        name: "Overtime",
        i18nKey: "overtime",
        url: "/hrd/overtime",
        icon: "moon",
        permission: "overtime.read",
      },
      {
        name: "Evaluation",
        i18nKey: "evaluation",
        url: "/hrd/evaluation",
        icon: "check-square",
        permission: "evaluation.read",
      },
      {
        name: "Recruitment",
        i18nKey: "recruitment",
        url: "/hrd/recruitment",
        icon: "user-plus",
        permission: "recruitment.read",
      },
      {
        name: "Work Schedule",
        i18nKey: "workSchedule",
        url: "/hrd/work-schedule",
        icon: "calendar-check",
        permission: "work_schedule.read",
      },
      {
        name: "Holidays",
        i18nKey: "holidays",
        url: "/hrd/holidays",
        icon: "calendar",
        permission: "holiday.read",
      },
    ],
  },
  {
    name: "Reports",
    i18nKey: "reports",
    icon: "bar-chart-3",
    url: "/reports",
    permission: "report.view",
    children: [
      {
        name: "Sales Overview",
        i18nKey: "salesOverview",
        url: "/reports/sales-overview",
        icon: "trending-up",
        permission: "report_sales_overview.read",
      },
      {
        name: "Top Product",
        i18nKey: "topProduct",
        url: "/reports/product-analysis",
        icon: "bar-chart-3",
        permission: "report_product_analysis.read",
      },
      {
        name: "Geo Performance",
        i18nKey: "geoPerformance",
        url: "/reports/geo-performance",
        icon: "map",
        permission: "report_geo_performance.read",
      },
      {
        name: "Customer Research",
        i18nKey: "customerResearch",
        url: "/reports/customer-research",
        icon: "users",
        permission: "report_customer_research.read",
      },
      {
        name: "Supplier Research",
        i18nKey: "supplierResearch",
        url: "/reports/supplier-research",
        icon: "truck",
        permission: "report_supplier_research.read",
      },
    ],
  },
  {
    name: "Master Data",
    i18nKey: "masterData",
    icon: "database",
    url: "/master-data",
    children: [
      {
        name: "Geographic",
        i18nKey: "geographic",
        url: "/master-data/geographic",
        icon: "globe",
        permission: "geographic.read",
      },
      {
        name: "Organization",
        i18nKey: "organization",
        url: "/master-data/organization",
        icon: "building",
        children: [
          {
            name: "Company",
            i18nKey: "company",
            url: "/master-data/company",
            icon: "building",
            permission: "company.read",
          },
          {
            name: "Divisions",
            i18nKey: "divisions",
            url: "/master-data/divisions",
            icon: "layers",
            permission: "division.read",
          },
          {
            name: "Job Positions",
            i18nKey: "jobPositions",
            url: "/master-data/job-positions",
            icon: "user-cog",
            permission: "job_position.read",
          },
          {
            name: "Business Units",
            i18nKey: "businessUnits",
            url: "/master-data/business-units",
            icon: "layout-list",
            permission: "business_unit.read",
          },
          {
            name: "Business Types",
            i18nKey: "businessTypes",
            url: "/master-data/business-types",
            icon: "tag",
            permission: "business_type.read",
          },
          {
            name: "Areas",
            i18nKey: "areas",
            url: "/master-data/areas",
            icon: "map",
            permission: "area.read",
          },
        ],
      },
      {
        name: "Employees",
        i18nKey: "employees",
        url: "/master-data/employees",
        icon: "users",
        permission: "employee.read",
      },
      {
        name: "Banks",
        i18nKey: "banks",
        url: "/master-data/banks",
        icon: "landmark",
        permission: "bank.read",
      },
      {
        name: "Supplier",
        i18nKey: "supplier",
        url: "/master-data/supplier",
        icon: "truck",
        children: [
          {
            name: "Suppliers",
            i18nKey: "suppliers",
            url: "/master-data/suppliers",
            icon: "truck",
            permission: "supplier.read",
          },
          {
            name: "Supplier Types",
            i18nKey: "supplierTypes",
            url: "/master-data/supplier-types",
            icon: "tag",
            permission: "supplier_type.read",
          },
        ],
      },
      {
        name: "Customer",
        i18nKey: "customer",
        url: "/master-data/customer",
        icon: "user",
        children: [
          {
            name: "Customers",
            i18nKey: "customers",
            url: "/master-data/customers",
            icon: "user-check",
            permission: "customer.read",
          },
          {
            name: "Customer Types",
            i18nKey: "customerTypes",
            url: "/master-data/customer-types",
            icon: "tag",
            permission: "customer_type.read",
          },
        ],
      },
      {
        name: "Product",
        i18nKey: "product",
        url: "/master-data/product",
        icon: "package",
        children: [
          {
            name: "Products",
            i18nKey: "products",
            url: "/master-data/products",
            icon: "package",
            permission: "product.read",
          },
          {
            name: "Categories",
            i18nKey: "categories",
            url: "/master-data/product-categories",
            icon: "folder-tree",
            permission: "product_category.read",
          },
          {
            name: "Brands",
            i18nKey: "brands",
            url: "/master-data/product-brands",
            icon: "tag",
            permission: "product_brand.read",
          },
          {
            name: "Segments",
            i18nKey: "segments",
            url: "/master-data/product-segments",
            icon: "percent",
            permission: "product_segment.read",
          },
          {
            name: "Types",
            i18nKey: "types",
            url: "/master-data/product-types",
            icon: "tag",
            permission: "product_type.read",
          },
          {
            name: "Packaging",
            i18nKey: "packaging",
            url: "/master-data/packaging",
            icon: "box",
            permission: "packaging.read",
          },
          {
            name: "Unit of Measure",
            i18nKey: "unitOfMeasure",
            url: "/master-data/uom",
            icon: "hammer",
            permission: "uom.read",
          },
          {
            name: "Procurement Types",
            i18nKey: "procurementTypes",
            url: "/master-data/procurement-types",
            icon: "shopping-cart",
            permission: "procurement_type.read",
          },
        ],
      },
      {
        name: "Warehouses",
        i18nKey: "warehouses",
        url: "/master-data/warehouses",
        icon: "warehouse",
        permission: "warehouse.read",
      },
      {
        name: "Payment & Courier",
        i18nKey: "paymentCourier",
        url: "/master-data/payment-courier",
        icon: "credit-card",
        children: [
          {
            name: "Courier Agencies",
            i18nKey: "courierAgencies",
            url: "/master-data/courier-agencies",
            icon: "truck",
            permission: "courier_agency.read",
          },
          {
            name: "SO Sources",
            i18nKey: "soSources",
            url: "/master-data/so-sources",
            icon: "file-text",
            permission: "so_source.read",
          },
        ],
      },
      {
        name: "Leave Types",
        i18nKey: "leaveTypes",
        url: "/master-data/leave-types",
        icon: "calendar",
        permission: "leave_type.read",
      },
      {
        name: "Users",
        i18nKey: "users",
        url: "/master-data/users",
        icon: "users",
        permission: "user.read",
      },
    ],
  },
  {
    name: "AI Assistant",
    i18nKey: "aiAssistant",
    icon: "sparkles",
    url: "/ai-assistant",
    children: [
      {
        name: "Chatbot",
        i18nKey: "chatbot",
        url: "/ai-chatbot",
        icon: "bot",
        permission: "ai_chatbot.view",
      },
      {
        name: "Settings",
        i18nKey: "settings",
        url: "/ai-settings",
        icon: "settings",
        permission: "ai_settings.view",
      },
    ],
  },
];
