import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { useTranslations } from "next-intl";
import {
  useCreateCustomer,
  useUpdateCustomer,
  useCustomerFormData,
} from "./use-customers";
import type { Customer } from "../types";

const formSchema = z.object({
  name: z
    .string()
    .min(2, "Name must be at least 2 characters")
    .max(200, "Name cannot exceed 200 characters"),
  customer_type_id: z.string().optional(),
  address: z.string().max(500, "Address cannot exceed 500 characters").optional(),
  village_id: z.string().optional(),
  email: z.string().email("Invalid email").max(100).optional().or(z.literal("")),
  website: z.string().max(200).optional(),
  npwp: z.string().max(30).optional(),
  contact_person: z.string().max(100).optional(),
  notes: z.string().max(1000).optional(),
  latitude: z.string().optional(),
  longitude: z.string().optional(),
  is_active: z.boolean(),
});

type FormData = z.infer<typeof formSchema>;

export interface UseCustomerFormProps {
  open: boolean;
  onClose: () => void;
  editingItem: Customer | null;
}

export function useCustomerForm({ open, onClose, editingItem }: UseCustomerFormProps) {
  const t = useTranslations("customer.customer");
  const tCommon = useTranslations("customer.common");
  const tValidation = useTranslations("customer.validation");

  const createMutation = useCreateCustomer();
  const updateMutation = useUpdateCustomer();
  const { data: formDataData } = useCustomerFormData({ enabled: open });

  const customerTypes = formDataData?.data?.customer_types ?? [];

  const isEditing = !!editingItem;
  const isSubmitting = createMutation.isPending || updateMutation.isPending;

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      customer_type_id: "",
      address: "",
      village_id: "",
      email: "",
      website: "",
      npwp: "",
      contact_person: "",
      notes: "",
      latitude: "",
      longitude: "",
      is_active: true,
    },
  });

  useEffect(() => {
    if (open) {
      if (editingItem) {
        form.reset({
          name: editingItem.name,
          customer_type_id: editingItem.customer_type_id ?? "",
          address: editingItem.address ?? "",
          village_id: editingItem.village_id ?? "",
          email: editingItem.email ?? "",
          website: editingItem.website ?? "",
          npwp: editingItem.npwp ?? "",
          contact_person: editingItem.contact_person ?? "",
          notes: editingItem.notes ?? "",
          latitude: editingItem.latitude?.toString() ?? "",
          longitude: editingItem.longitude?.toString() ?? "",
          is_active: editingItem.is_active,
        });
      } else {
        form.reset({
          name: "",
          customer_type_id: "",
          address: "",
          village_id: "",
          email: "",
          website: "",
          npwp: "",
          contact_person: "",
          notes: "",
          latitude: "",
          longitude: "",
          is_active: true,
        });
      }
    }
  }, [open, editingItem, form]);

  const onSubmit = async (data: FormData) => {
    try {
      // Clean empty strings to undefined and convert lat/lng to numbers
      const payload = {
        ...data,
        customer_type_id: data.customer_type_id || undefined,
        village_id: data.village_id || undefined,
        email: data.email || undefined,
        website: data.website || undefined,
        npwp: data.npwp || undefined,
        contact_person: data.contact_person || undefined,
        notes: data.notes || undefined,
        address: data.address || undefined,
        latitude: data.latitude ? Number(data.latitude) : null,
        longitude: data.longitude ? Number(data.longitude) : null,
      };

      if (isEditing) {
        await updateMutation.mutateAsync({
          id: editingItem.id,
          data: payload,
        });
        toast.success(t("updateSuccess"));
      } else {
        await createMutation.mutateAsync({
          ...payload,
          code: "", // Auto-generated by backend
        });
        toast.success(t("createSuccess"));
      }
      onClose();
    } catch {
      toast.error(isEditing ? tCommon("error_update") : "Failed to create customer");
    }
  };

  return {
    form,
    t,
    tCommon,
    tValidation,
    isEditing,
    isSubmitting,
    customerTypes,
    onSubmit: form.handleSubmit(onSubmit),
  };
}
